import { Linter } from "eslint";
import yaml from "js-yaml";

function generateYAMLCommentBlock(): string {
  return `# This configuration was generated by
# \`eslint-generate-todo\` (http://github.com/doximity/eslint-generate-todo)
#
# on ${new Date().toISOString()}.
#
# It contains all the known ESLint errors/warnings, and prevents them from
# showing up as errors until devs can remove them from the code base.
# Regenerate this file as errors are fixed.

`;
}

export function renderAsYAML(config: Linter.Config): string {
  return `${generateYAMLCommentBlock()}${yaml.dump(config)}`;
}

export function renderAsJSON(config: Linter.Config): string {
  return JSON.stringify(config, null, 2);
}
